spring:
  application:
    name: service_c
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://postgres:5432/service_c_db}
    password: ${DATASOURCE_PASSWORD:password}
    username: ${DATASOURCE_USERNAME:user}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
    level:
      org.springframework: DEBUG # Будет виден процесс создания бинов
      mentorship.roadmap.microservices.service_c: DEBUG