spring:
  application:
    name: service_a

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://mongo:27017/service-a-db}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      auto-offset-reset: earliest
      group-id: service-a
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

service-b:
  uri: ${SERVICE_B_URL:http://service-b:8080}